[book]
authors = ["AngeCI"]
language = "en"
multilingual = false
src = "src"
title = "AngeCI Docs"
description = "The documentation of AngeCI's softwares and packages."

[build]
build-dir = "book"

[output.html]
site-url = "/"
default-theme = "light"
preferred-dark-theme = "ayu"
